version: '2'
services:
 mysql-master:
   restart: always
   build: master/
   volumes:
   - ./master/db:/var/lib/mysql
   command: [--character-set-server=utf8mb4,--collation-server=utf8mb4_unicode_ci,--innodb-use-native-aio=0]
   environment:
    MYSQL_ROOT_PASSWORD: d3eb23f714529f1e73f934876d1b39
   ports:
   - 3307:3306
   container_name: o2o-mysql-master
   mem_limit: 8g
   logging: 
     driver: 'json-file'
     options: 
       max-size: '5g'

 mysql-slave:
   restart: always
   build: slave/
   volumes:
   - ./slave/db:/var/lib/mysql
   command: [--character-set-server=utf8mb4,--collation-server=utf8mb4_unicode_ci,--innodb-use-native-aio=0]
   environment:
    MYSQL_ROOT_PASSWORD: d3eb23f714529f1e73f934876d1b39
   ports:
   - 3308:3306
   container_name: o2o-mysql-slave
   mem_limit: 8g
   logging: 
     driver: 'json-file'
     options: 
       max-size: '5g'

networks:
  default:
    external:
      name: o2o-network
