version: '2'
services:
 mysql-master:
   restart: always
   build: master/
   image: registry.vcredit.com/o2o/mysql-master
   volumes:
   - /data/www/docker-mysql-replication/master/db:/var/lib/mysql
   - /etc/localtime:/etc/localtime
   command: [--character-set-server=utf8mb4,--collation-server=utf8mb4_unicode_ci]
   environment:
    MYSQL_ROOT_PASSWORD: vcredit_o2o
   ports:
   - 3307:3306
   container_name: o2o-mysql-master
   mem_limit: 8g

 mysql-slave:
   restart: always
   build: slave/
   image: registry.vcredit.com/o2o/mysql-slave
   volumes:
   - /data/www/docker-mysql-replication/slave/db:/var/lib/mysql
   - /etc/localtime:/etc/localtime
   command: [--character-set-server=utf8mb4,--collation-server=utf8mb4_unicode_ci]
   environment:
    MYSQL_ROOT_PASSWORD: vcredit_o2o
   ports:
   - 3308:3306
   container_name: o2o-mysql-slave
   mem_limit: 8g

networks:
  default:
    external:
      name: o2o-network
